# **Introduction**


Let us consider you just joined a startup as a data analyst and you have been assigned to support the team to drive insights about the customers base. Your manager shared the dataset and here is your opportunity to showcase your python skills and use the Pandas package to perform the analysis.

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('pandas_project_data.csv')
df.head()

,customer_id,year_of_birth,educational_level,marital_status,annual_income,purhcase_date,recency,online_purchases,store_purchases,complaints,calls,intercoms
0,20201701,1978,Graduation,Divorced,66098.0,12/19/2013,13,10,2,0,4,11
1,20201702,1991,Graduation,Divorced,64690.0,5/14/2013,64,26,9,0,3,7
2,20201703,1968,PhD,Divorced,47150.0,3/19/2013,62,10,2,0,3,11
3,20201704,1954,Graduation,Married,52714.0,1/3/2013,99,1,10,0,4,11
4,20201705,1982,Graduation,Married,29912.0,4/10/2014,19,16,11,0,4,7

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 499 entries, 0 to 498
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer_id        499 non-null    int64
 1   year_of_birth      499 non-null    int64
 2   educational_level  499 non-null    str
 3   marital_status     499 non-null    str
 4   annual_income      486 non-null    float64
 5   purhcase_date      499 non-null    str
 6   recency            499 non-null    int64
 7   online_purchases   499 non-null    int64
 8   store_purchases    499 non-null    int64
 9   complaints         499 non-null    int64
 10  calls              499 non-null    int64
 11  intercoms          499 non-null    int64
dtypes: float64(1), int64(8), str(3)
memory usage: 46.9 KB

In [4]:
df[df.isna().any(axis=1)] #Check null

,customer_id,year_of_birth,educational_level,marital_status,annual_income,purhcase_date,recency,online_purchases,store_purchases,complaints,calls,intercoms
10,20201711,1962,Graduation,Divorced,NaN,9/7/2013,20,14,3,2,3,7
27,20201728,1999,Graduation,Single,NaN,1/17/2014,80,18,12,0,4,11
43,20201744,1986,Graduation,Married,NaN,4/4/2012,69,9,7,0,4,11
48,20201749,1996,Graduation,Relationship,NaN,10/14/2014,19,11,12,3,3,2
58,20201759,1964,Graduation,Single,NaN,4/11/2012,84,7,1,0,4,11
71,20201772,1946,Graduation,Married,NaN,4/9/2013,82,17,13,1,3,11
90,20201791,1965,Master,Divorced,NaN,3/9/2012,90,12,5,1,4,11
91,20201792,1983,PhD,Married,NaN,4/19/2014,84,26,0,3,3,11
92,20201793,1973,Master,Married,NaN,7/26/2014,41,3,11,2,3,11
128,20201829,1983,PhD,Relationship,NaN,1/17/2014,67,23,1,0,3,7
133,20201834,1956,Graduation,Widowed,NaN,10/8/2013,73,6,5,0,3,7
312,20202013,1958,Graduation,Divorced,NaN,9/26/2013,61,22,10,0,6,7
319,20202020,1991,PhD,Married,NaN,11/24/2013,32,9,10,0,3,7

# Ex1. Fill missing in annual_income with mean of incomme

In [5]:
df.annual_income = df.annual_income.fillna(df.annual_income.mean())
df[df.isna().any(axis=1)] #Check null

Empty DataFrame
Columns: [customer_id, year_of_birth , educational_level, marital_status, annual_income, purhcase_date, recency, online_purchases, store_purchases, complaints, calls, intercoms]
Index: []

#Ex2. Show a list of customers having annual income greater than $50.000

In [6]:
df[df.annual_income > 50000]

,customer_id,year_of_birth,educational_level,marital_status,annual_income,purhcase_date,recency,online_purchases,store_purchases,complaints,calls,intercoms
0,20201701,1978,Graduation,Divorced,66098.0,12/19/2013,13,10,2,0,4,11
1,20201702,1991,Graduation,Divorced,64690.0,5/14/2013,64,26,9,0,3,7
3,20201704,1954,Graduation,Married,52714.0,1/3/2013,99,1,10,0,4,11
5,20201706,1947,Graduation,Relationship,50655.0,8/19/2013,76,8,0,4,3,11
6,20201707,1960,Graduation,Single,69751.0,3/9/2014,80,27,10,0,6,11
...,...,...,...,...,...,...,...,...,...,...,...,...
491,20202192,1981,Graduation,Single,64783.0,9/12/2013,40,21,7,0,3,7
493,20202194,1965,Graduation,Divorced,55659.0,8/20/2014,55,7,12,0,3,11
494,20202195,1974,Master,Married,67029.0,10/6/2013,62,22,13,0,3,11
495,20202196,1989,Graduation,Widowed,55075.0,6/23/2013,4,7,11,4,3,11
498,20202199,1952,Graduation,Relationship,71902.0,9/6/2013,95,13,6,2,5,11

# Ex3. Show a list of customer ids having annual income > $50k and complaints > 2

In [7]:
df[(df['complaints'] > 2) & (df['annual_income'] > 50000)]["customer_id"]

5      20201706
9      20201710
16     20201717
23     20201724
30     20201731
48     20201749
59     20201760
61     20201762
91     20201792
100    20201801
110    20201811
112    20201813
129    20201830
139    20201840
170    20201871
195    20201896
196    20201897
205    20201906
211    20201912
213    20201914
214    20201915
229    20201930
236    20201937
239    20201940
244    20201945
255    20201956
259    20201960
262    20201963
268    20201969
307    20202008
320    20202021
326    20202027
333    20202034
334    20202035
335    20202036
337    20202038
359    20202060
393    20202094
411    20202112
418    20202119
425    20202126
438    20202139
457    20202158
458    20202159
472    20202173
481    20202182
487    20202188
495    20202196
Name: customer_id, dtype: int64

# Ex4. Show a list of customers purchasing in April

In [8]:
df['purhcase_date'] = pd.to_datetime(df.purhcase_date)

In [9]:
df[df['purhcase_date'].dt.month==4]

,customer_id,year_of_birth,educational_level,marital_status,annual_income,purhcase_date,recency,online_purchases,store_purchases,complaints,calls,intercoms
4,20201705,1982,Graduation,Married,29912.000000,2014-04-10,19,16,11,0,4,7
19,20201720,1961,Graduation,Single,74855.000000,2013-04-15,7,15,3,0,3,2
20,20201721,1992,PhD,Single,57579.000000,2013-04-20,78,12,12,1,6,11
32,20201733,1961,High School,Single,77285.000000,2013-04-25,75,8,0,0,4,11
41,20201742,1955,Graduation,Married,57629.000000,2012-04-04,28,25,6,0,3,11
42,20201743,1954,PhD,Married,43555.000000,2012-04-27,78,3,13,3,4,11
43,20201744,1986,Graduation,Married,52037.746914,2012-04-04,69,9,7,0,4,11
58,20201759,1964,Graduation,Single,52037.746914,2012-04-11,84,7,1,0,4,11
61,20201762,1989,Graduation,Divorced,96193.000000,2013-04-21,79,1,6,4,3,11
65,20201766,1992,Graduation,Relationship,28847.000000,2012-04-20,19,10,13,1,3,7
71,20201772,1946,Graduation,Married,52037.746914,2013-04-09,82,17,13,1,3,11
72,20201773,1983,High School,Divorced,44657.000000,2012-04-09,63,11,4,2,3,11
89,20201790,1957,Master,Divorced,41296.000000,2014-04-15,82,13,8,0,3,11
91,20201792,1983,PhD,Married,52037.746914,2014-04-19,84,26,0,3,3,11
97,20201798,1987,Graduation,Relationship,47507.000000,2013-04-19,71,20,11,0,6,11
109,20201810,1986,High School,Divorced,27917.000000,2014-04-12,26,11,10,0,3,11
110,20201811,1992,Graduation,Divorced,59557.000000,2014-04-13,43,0,7,3,3,11
120,20201821,1954,PhD,Widowed,54238.000000,2013-04-01,19,4,12,2,3,11
139,20201840,1944,Graduation,Relationship,59258.000000,2014-04-13,59,7,10,5,4,7
144,20201845,1967,PhD,Married,54757.000000,2014-04-03,83,15,1,1,4,2
147,20201848,1947,Master,Single,56185.000000,2012-04-20,10,11,6,0,3,7
155,20201856,1976,Master,Divorced,35326.000000,2013-04-08,22,14,11,0,5,11
163,20201864,1974,Graduation,Divorced,49917.000000,2014-04-21,7,20,5,0,3,11
166,20201867,1953,PhD,Relationship,47207.000000,2013-04-11,36,10,10,5,6,11
185,20201886,1988,Master,Married,52495.000000,2012-04-14,25,4,10,0,3,11
188,20201889,1943,Master,Single,15753.000000,2014-04-13,4,18,9,5,3,11
194,20201895,1954,PhD,Relationship,47941.000000,2014-04-19,92,9,7,1,3,11
203,20201904,1961,Graduation,Single,35349.000000,2014-04-13,23,13,7,3,3,11
233,20201934,1945,Graduation,Relationship,74645.000000,2013-04-17,77,11,9,0,3,11
280,20201981,1971,Graduation,Widowed,61469.000000,2013-04-17,92,16,10,1,4,11
282,20201983,1971,PhD,Single,35571.000000,2014-04-23,1,1,4,0,3,11
283,20201984,1994,Graduation,Single,62995.000000,2013-04-24,55,3,11,2,6,7
289,20201990,1956,PhD,Married,42566.000000,2014-04-11,85,7,7,0,3,11
306,20202007,1968,Graduation,Widowed,56471.000000,2013-04-15,60,26,10,1,5,11
310,20202011,1998,Graduation,Widowed,41769.000000,2014-04-11,25,26,4,0,3,11
328,20202029,1967,Graduation,Divorced,78613.000000,2014-04-24,97,19,12,2,4,2
338,20202039,1999,Graduation,Married,65686.000000,2013-04-03,42,13,7,1,4,11
359,20202060,1987,Master,Divorced,56175.000000,2013-04-05,66,7,2,5,3,11
372,20202073,1975,Graduation,Relationship,41005.000000,2013-04-27,34,6,12,0,3,11
383,20202084,1985,Graduation,Single,19393.000000,2014-04-05,72,5,0,0,3,11
385,20202086,1941,PhD,Widowed,50877.000000,2014-04-28,47,23,7,0,6,11
392,20202093,1943,Graduation,Single,78239.000000,2013-04-28,40,13,0,0,6,2
420,20202121,1966,PhD,Single,15524.000000,2014-04-19,58,18,2,4,5,11
437,20202138,1967,Graduation,Widowed,25321.000000,2013-04-15,73,20,12,4,6,11
447,20202148,1963,Graduation,Relationship,38793.000000,2013-04-22,29,6,13,0,5,11
454,20202155,1999,Master,Relationship,64474.000000,2013-04-21,3,6,2,0,4,11
463,20202164,1964,PhD,Divorced,66614.000000,2014-04-27,66,4,7,0,4,7
464,20202165,1981,Graduation,Married,44328.000000,2012-04-21,96,5,6,1,6,2
483,20202184,1979,Graduation,Divorced,56503.000000,2014-04-26,93,20,1,0,3,7
489,20202190,1978,Master,Married,25411.000000,2014-04-26,78,1,13,0,5,11

# Ex5. Show a list of customers with purchases > 5

In [10]:
df[df.online_purchases + df.store_purchases > 5]

,customer_id,year_of_birth,educational_level,marital_status,annual_income,purhcase_date,recency,online_purchases,store_purchases,complaints,calls,intercoms
0,20201701,1978,Graduation,Divorced,66098.0,2013-12-19,13,10,2,0,4,11
1,20201702,1991,Graduation,Divorced,64690.0,2013-05-14,64,26,9,0,3,7
2,20201703,1968,PhD,Divorced,47150.0,2013-03-19,62,10,2,0,3,11
3,20201704,1954,Graduation,Married,52714.0,2013-01-03,99,1,10,0,4,11
4,20201705,1982,Graduation,Married,29912.0,2014-04-10,19,16,11,0,4,7
...,...,...,...,...,...,...,...,...,...,...,...,...
494,20202195,1974,Master,Married,67029.0,2013-10-06,62,22,13,0,3,11
495,20202196,1989,Graduation,Widowed,55075.0,2013-06-23,4,7,11,4,3,11
496,20202197,1964,PhD,Relationship,34103.0,2013-07-26,60,24,3,5,3,7
497,20202198,1963,Graduation,Divorced,48507.0,2013-06-04,75,5,12,2,3,7
498,20202199,1952,Graduation,Relationship,71902.0,2013-09-06,95,13,6,2,5,11

# Ex6. Average Income of customers with Divorced status

In [11]:
df[df.marital_status == 'Divorced']['annual_income'].mean()

np.float64(52874.471257716046)

# Ex7. Show a frequency of complains against customers.

Example:
There are 4 customers with 3 complaints, 15 customers with 1 complaints....

In [12]:
df['complaints'].value_counts()

complaints
0    290
1     69
3     43
2     41
4     34
5     22
Name: count, dtype: int64

# Ex8. Show the average income of 30-40 years old customers

In [13]:
import datetime

df['age'] = datetime.datetime.now().year - df['year_of_birth ']
df[(df['age'] >= 30) & (df['age'] <= 40)]['annual_income'].mean()

np.float64(50181.6804526749)

# Ex 9. Which educational level haves the highest average annual income?

In [14]:
max_val = 0
name = ''
for edu_level in df['educational_level'].unique():
    temp = df[df.educational_level == edu_level]['annual_income'].mean()
    if temp > max_val:
        max_val = temp
        name = edu_level
print(name, max_val)

Graduation 53745.35500125976

# Ex 10. Show max income in each group of educational_level

In [15]:
df.groupby('educational_level')['annual_income'].max()

educational_level
Graduation     98411.0
High School    77285.0
Master         87455.0
PhD            99130.0
Name: annual_income, dtype: float64

# Ex11. Show total sale of each group of year of birth and marital_status

In [16]:
df["purchases"] = df["online_purchases"] + df["store_purchases"]
df.groupby(["year_of_birth ","marital_status"])["purchases"].sum()
#df.groupby(["year_of_birth ","marital_status"])["online_purchases"].sum() + df.groupby(["year_of_birth ","marital_status"])["store_purchases"].sum()

year_of_birth   marital_status
1940            Divorced          29
                Married           54
                Relationship      59
                Single            51
                Widowed           19
                                  ..
1999            Divorced          62
                Married           45
                Relationship      94
                Single            62
                Widowed           47
Name: purchases, Length: 236, dtype: int64

# Ex12. Categorize the annual income into three values: low, medium and high as follow:

low: income < mean - 10% mean

High: income > mean + 10% mean

medium: the remaining

In [17]:
mean_income = df['annual_income'].mean()
df['annual_income_cate'] = 'medium'
df.loc[df['annual_income'] > mean_income * 1.1, 'annual_income_cate'] = 'high'
df.loc[df['annual_income'] < mean_income * 0.9, 'annual_income_cate'] = 'low'
df.head()

TypeError: Invalid value 'high' for dtype 'float64'

# To each group of educational_level, the item has a corresponding price provided in the item-price.csv file

In [ ]:
df_price = pd.read_csv("price.csv")
df_price

  educational_level  price
0        Graduation    150
1               PhD    180
2            Master    160
3             Basic    130
4       High School    100

# Ex 13. Add an "Amount" column to show the purchase amount for each customer.

In [ ]:
merge_result = df.merge(df_price,left_on="educational_level",right_on="educational_level")
merge_result

,customer_id,year_of_birth,educational_level,marital_status,annual_income,purhcase_date,recency,online_purchases,store_purchases,complaints,calls,intercoms,purchases,annual_income_cate,price
0,20201701,1982,Graduation,Single,58138.0,9/4/2012,58,8,4,0,3,11,12,high,150
1,20201702,1950,Graduation,Married,46344.0,3/8/2014,38,1,2,0,3,11,3,medium,150
2,20201703,1965,Graduation,Divorced,71613.0,8/21/2013,26,8,10,0,3,11,18,high,150
3,20201704,1984,Graduation,Relationship,26646.0,2/10/2014,26,2,4,0,3,11,6,low,150
4,20201707,1971,Graduation,Divorced,55635.0,11/13/2012,34,7,7,0,3,11,14,medium,150
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
494,20202145,1992,High School,Married,20130.0,3/17/2014,99,1,3,0,3,11,4,low,100
495,20202154,1975,High School,Married,70829.0,12/1/2013,87,4,8,0,3,11,12,high,100
496,20202157,1957,High School,Single,89572.0,9/15/2012,44,7,9,0,3,11,16,high,100
497,20202160,1957,High School,Relationship,58723.0,9/25/2012,78,5,6,0,0,11,11,high,100
498,20202190,1952,High School,Widow,28457.0,10/28/2012,96,4,4,0,3,11,8,low,100

In [ ]:
merge_result["Amount"] = (merge_result["online_purchases"]+merge_result["store_purchases"])*merge_result["price"]
merge_result

,customer_id,year_of_birth,educational_level,marital_status,annual_income,purhcase_date,recency,online_purchases,store_purchases,complaints,calls,intercoms,purchases,annual_income_cate,price,Amount
0,20201701,1982,Graduation,Single,58138.0,9/4/2012,58,8,4,0,3,11,12,high,150,1800
1,20201702,1950,Graduation,Married,46344.0,3/8/2014,38,1,2,0,3,11,3,medium,150,450
2,20201703,1965,Graduation,Divorced,71613.0,8/21/2013,26,8,10,0,3,11,18,high,150,2700
3,20201704,1984,Graduation,Relationship,26646.0,2/10/2014,26,2,4,0,3,11,6,low,150,900
4,20201707,1971,Graduation,Divorced,55635.0,11/13/2012,34,7,7,0,3,11,14,medium,150,2100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
494,20202145,1992,High School,Married,20130.0,3/17/2014,99,1,3,0,3,11,4,low,100,400
495,20202154,1975,High School,Married,70829.0,12/1/2013,87,4,8,0,3,11,12,high,100,1200
496,20202157,1957,High School,Single,89572.0,9/15/2012,44,7,9,0,3,11,16,high,100,1600
497,20202160,1957,High School,Relationship,58723.0,9/25/2012,78,5,6,0,0,11,11,high,100,1100
498,20202190,1952,High School,Widow,28457.0,10/28/2012,96,4,4,0,3,11,8,low,100,800